### ISSUE TITLE
homography mapping crash

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/uvc_ros_driver#17]
the node (or even computer) crashes if the number of cameras is less than the number of homography mappings

**Comment by dominiho** [comment]
resolved in master (#18)

**Comment by ChristophTobler** [comment]
still happens, but not crashing. The error I get when my homography mappings looks like that:  [[0,1], [2,3], [4,5]] but I just use 2 cameras:

Waiting on device...
Device connected
current projection model not supported
